<?php
include_once 'header.phtml';
?>
<v-layout row wrap>
  <v-flex xs12>
      <question
        v-for="(question, index) in randomizedQuestions"
        :question="question"
        :key="index"
        :progress="progress"
        chapter-num="8"
        @guessed="checkAnswer"
        @forfeited="forfeitQuestion"
      ></question>
    </div>
  </v-flex>
</v-layout>
<?php
include_once 'footer.phtml';
?>
