<?php
$uri = $_SERVER['REQUEST_URI'];

$uriParts = explode("/", $uri);
$chapter = $uriParts[count($uriParts) -1];
$chapterJs = substr($chapter, 0, strpos($chapter, '.')) . ".js"; // used in footer
$chapterNum = filter_var($chapter, FILTER_SANITIZE_NUMBER_INT);
?>

<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title>em8e Test Your Knowledge <?php echo $chapter ? "&mdash; Chapter $chapterNum" : ""; ?></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Place favicon.ico in the root directory -->

  <link rel="stylesheet" href="assets/css/normalize.css">

  <!-- VUETIFY CSS -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet">
  <!--<link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css" rel="stylesheet">-->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/vuetify/1.5.16/vuetify.css" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/main.css">
</head>

<body>

  <v-app id="app" v-cloak>
    <v-navigation-drawer
        app
        v-model="drawer"
        class="primary"
        dark
        temporary
    >
      <v-toolbar flat class="primary darken-1">
        <v-list class="pa-0">
          <v-list-tile>
            <v-list-tile-content>
                <v-btn flat href="index.phtml">em8e Test Your Understanding</v-btn>
            </v-list-tile-content>
          </v-list-tile>
        </v-list>
      </v-toolbar>
      <v-list
        v-for="index in 10"
        :key="'drawer-link-' + index"
      >
        <v-list-tile :href="'chapter' + index + '.phtml'">
          <v-list-tile-action>
            <v-icon>book</v-icon>
          </v-list-tile-action>

          <v-list-tile-content>
            <v-list-tile-title>{{ index }}) {{ chapterTitles[index - 1] }}</v-list-tile-title>
          </v-list-tile-content>
        </v-list-tile>
      </v-list>
    </v-navigation-drawer>
    <v-toolbar
        app
        class="blue"
        dark
    >
      <v-toolbar-side-icon @click="drawer ? drawer = false : drawer = true"></v-toolbar-side-icon>
      <v-toolbar-title>
        <template v-if="!isIndexPage">
          Chapter <?php echo $chapterNum; ?> &ndash; {{ chapterTitles[<?php echo $chapterNum - 1; ?>] }}
        </template>
        <template v-else>
          em8e Test Your Understanding
        </template>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <v-menu offset-y v-if="!isIndexPage">
        <template v-slot:activator="{ on }">
          <v-btn color="red darken-2" dark v-on="on">
            Score: {{ totalPoints }}/100 points
          </v-btn>
        </template>
        <v-list>
          <v-list-tile
              v-for="(question, index) in progress"
              :key="'score-bug-' + index"
          >
            <v-list-tile-title>Q{{ (index + 1) + ') ' + question.points }}/20</v-list-tile-title>
          </v-list-tile>
        </v-list>
      </v-menu>
    </v-toolbar>
    <v-content>
      <v-container grid-list-sm>
        <?php
          if($chapterNum):
        ?>
        <v-layout row wrap>
          <v-flex xs12 text-xs-center>
            <v-btn
                flat
                color="info darken-2"
                href="
                <?php
                  if($chapterNum == 1){
                    echo 'index.phtml';
                  } else {
                    echo 'chapter' . ($chapterNum-1) . '.phtml';
                  }
                ?>
                "
            >
              <v-icon>keyboard_arrow_left</v-icon>
              <?php
              if($chapterNum == 1){
                echo 'Quiz Homepage';
              } else {
                echo 'Chapter ' . ($chapterNum-1);
              }
              ?>

            </v-btn>
            <span class="current-chapter"><strong>Chapter <?php echo $chapterNum; ?></strong></span>
            <v-btn
                flat
                right
                color="info darken-2"
                href="
                <?php
                if($chapterNum == 10){
                  echo 'index.phtml';
                } else {
                  echo 'chapter' . ($chapterNum+1) . '.phtml';
                }
                ?>
                "
            >
              <?php
              if($chapterNum == 10){
                echo 'Quiz Homepage';
              } else {
                echo 'Chapter ' . ($chapterNum+1);
              }
              ?> <v-icon>keyboard_arrow_right</v-icon>
            </v-btn>
          </v-flex>
        </v-layout>
        <?php
          endif;
        ?>


